### ISSUE TITLE
Love Frames: text input issue

### ISSUE THREAD

**Issue by easy82** [binji/love-nacl#18]
Löveliness doesn't seem to handle well text input fields, see example here:
http://archive.nikolairesokav.com/love/loveframes/loveframes-demo.love

Scroll down in the example list and select text input, then try to write some text in the window appearing. The cursor is blinking, but no text can be written. I've seen this in another text input example, see the links here:
https://love2d.org/forums/viewtopic.php?f=5&t=23304

**Comment by binji** [comment]
Duplicate of issue #4.

**Comment by marcocult** [comment]
This seem to be still happening. Textinput doesn't show anything when I type in it.
