### ISSUE TITLE
Love Frames: scissor issue

### ISSUE THREAD

**Issue by easy82** [binji/love-nacl#19]
Scissor doesn't seem to be OK in Love Frames, see example here:
http://archive.nikolairesokav.com/love/loveframes/loveframes-demo.love

Scroll down and up in the example list to see some buttons are out of the window even though they shouldn't. This can be seen in Column List, List, Tabs, Text examples as well.

**Comment by binji** [comment]
It's actually a stencil buffer issue.
Fixed in 8eb3918f600443529b3b16e1a2411393fdfd11cf

**Comment by easy82** [comment]
Is this fixed in 1.6? I still can see the artifact, however it's certainly not a deal-breaker. On the other side, the text input issue is fixed, thanks! :)

**Comment by binji** [comment]
No, I haven't pushed out a version with the fix yet. It'll be in v0.1.7

**Comment by easy82** [comment]
Ah, I see. All right!
