### ISSUE TITLE
Löveliness 0.1.8 examples does not work on left click

### ISSUE THREAD

**Issue by easy82** [binji/love-nacl#21]
As the title says, the examples does not work on left click sometimes, they just hang. On right click however, they load as they should.

I'm on Linux Mint 13, Chrome version 26.0.1410.63.

**Comment by easy82** [comment]
Maybe this is a duplicate of #8 ?

**Comment by binji** [comment]
I think this may be fixed in 3ae7c63281f4012f8ddca6256212823c868777cd

**Comment by easy82** [comment]
Yes! Thank you! And I really like the download screen, finally it doesn't look like it's broken when loading. :)
