### ISSUE TITLE
Everything seems to work! But I can't see anything happen?

### ISSUE THREAD

**Issue by Sheepolution** [binji/love-nacl#22]
"Everything seems to work", says the test. But when opening a game, or checking an example, nothing happens!

Google Chrome   26.0.1410.64 (Officiële build 193017) m
OS  Windows 
WebKit  537.31 (@147513)
JavaScript  V8 3.16.14.11
Flash   11.7.700.202
User-agent  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.64 Safari/537.31

**Comment by binji** [comment]
Can you open the Chrome developer tools, go to "Console" and paste the output here?

**Comment by karai17** [comment]
Everything works fine on my end, running Chrome 28 dev-m.

Console dump:
    got module message: download:0,0
    got module message: download:24423,0
    Done.
     passingclouds.love:1
    got module message: OK
    usage: 0 quota: 0 filesystem.js:89
    Got command: run params: 
     passingclouds.love:1
    got module message: setWindow:800,600

**Comment by Sheepolution** [comment]
Uncaught TypeError: Cannot call method 'appendChild' of undefined
Error in event handler for 'undefined': Cannot call method 'appendChild' of null TypeError: Cannot call method 'appendChild' of null
    at <anonymous>:188:31
    at chrome.Event.dispatchToListener (event_bindings:390:21)
    at chrome.Event.dispatch_ (event_bindings:376:27)
    at chrome.Event.dispatch (event_bindings:396:17)
    at miscellaneous_bindings:166:33
    at chrome.Event.dispatchToListener (event_bindings:390:21)
    at chrome.Event.dispatch_ (event_bindings:376:27)
    at chrome.Event.dispatch (event_bindings:396:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:254:22) event_bindings:380
got module message: download:0,0
got module message: download:24423,0
Done.
 passingclouds.love:1
got module message: OK
Uncaught TypeError: Cannot call method 'queryUsageAndQuota' of undefined 

This is what I get when I try to open http://commondatastorage.googleapis.com/loveliness/love/passingclouds.love
On other games I only get the last error.

**Comment by binji** [comment]
Thanks, that helps! I'll take a look...

**Comment by easy82** [comment]
I can confirm this here as well!

Whe new version of Löveliness (0.2.0) it only works if I right click and select "Open with LÖVELINESS". Simple left clicking or right clicking and selecting "New Tab" just opens a blank black page.

**Comment by Sheepolution** [comment]
Opening with the right-click method gives me the same result, with this error:
Download: url_loader_ is null?
 context_menu.html:1
got module message: download:0,24423 injected.js:271
downloading 0% injected.js:106
got module message: download:24423,24423 injected.js:271
downloading 100% injected.js:106
Done.
 context_menu.html:1
got module message: OK injected.js:271
checking filesystem... injected.js:106
Uncaught TypeError: Cannot call method 'queryUsageAndQuota' of undefined filesystem.js:101

**Comment by binji** [comment]
Yes, I've confirmed this bug. It should only happen on Chrome 26. It's fixed in 94c4b92653a8fac5831a25b2ce6f1570998dd588, and I'll push out v0.2.1 soon.

Sorry, everyone!

**Comment by easy82** [comment]
I hate to bring this up again, but it does not work for me. Left or right click on a LÖVE game generates the following error message in the console: "Only unpacked extensions and apps installed from the Chrome Web Store can load NaCl modules without enabling Native Client in about:flags.", while "Open with LÖVELINESS" option works flawlessly! I'm on version 0.2.1.

**Comment by binji** [comment]
This is a different bug, I'll open a new issue for it.
