### ISSUE TITLE
Mari0 crashed on v0.2.0

### ISSUE THREAD

**Issue by easy82** [binji/love-nacl#23]
Mari0 just crashed with the following error message in the console (I just paste the end of it here):

AL lib: ppapi.c:96: buffer underrun (buffer size=4096) (only buffering 0)
 context_menu.html:1
got module message: setWindow:800,600 chrome-extension://mompnkcmpbopandjnddeecgeeojegohc/injected.js:271
got module message: setWindow:800,448 chrome-extension://mompnkcmpbopandjnddeecgeeojegohc/injected.js:271
terminate called after throwing an instance of 'love::Exception'
 context_menu.html:1
NativeClient: NaCl module crashed context_menu.html:1
crash. :( 

After reloading the page, it works!

**Comment by binji** [comment]
When did it crash? I have seen it crash on load, and I've been trying to track it down...

**Comment by easy82** [comment]
Sorry, I've missed this one. So it crashed while loading, it did not reach the "Stabyourself" splash. I suspect some timeout-related problem in the background, but I might be wrong. Sometimes you might require stuff that isn't instantly ready?

**Comment by easy82** [comment]
I think the bug is in Mari0 itself. It has just frozen at the splash screen ("Loading GLADOS") on my Desktop (not in LÖVELINESS)!

**Comment by binji** [comment]
Aha! I've been wondering about that! Thanks for tracking this down. :)

I guess I'll close this bug now. :)
