### ISSUE TITLE
Love should be Updated

### ISSUE THREAD

**Issue by moocow1452** [binji/love-nacl#32]
Love's latest version is .8 or so, and some of the games on Stab Yourself are out of date with the current version. Could you see if you can patch it if you get a chance?

**Comment by binji** [comment]
I'm confused about what you want me to patch.

Some of the games on stabyourself.net are using the API of an older version of love (0.7.2). The best solution is to update those games to the most recent love (0.8).

As I mentioned in the #nacl IRC channel, it is not easy to support multiple love versions in LÖVELINESS; it likely would require a new executable for each version.

I've found that it's not too hard to update games from older versions of love. It's not fun, but AFAICT functionality is never removed, just renamed. See http://paste.ubuntu.com/6277477/ for a quick-and-dirty update of not pacman.

**Comment by moocow1452** [comment]
Ok. Was of the opinion that love was backwards compatible, but I guess not. Sorry to bother.

**Comment by binji** [comment]
No problem, they definitely don't seem too concerned about being backward compatible now, but maybe they will be after LÖVE 1.0?
